{% set name = "setuptools_scm" %}
{% set version = "3.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd25e1fb5e4d603dcf490f1fde40fb4c595b357795674c3e5cb7f6217ab39ea5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The blessed package to manage your versions by scm tags'

  description: |
    setuptools_scm handles managing your Python package versions in SCM
    metadata instead of declaring them as the version argument or in a SCM
    managed file.
    It also handles file finders for the supported SCMs.
  doc_url: https://github.com/pypa/setuptools_scm/
  dev_url: https://github.com/pypa/setuptools_scm/

extra:
  recipe-maintainers:
    - mdraw
